service: rxt-vehicle-booking-backend

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  runtime: 2048
  timeout: 15

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
